#ifndef SOFAORCOMMONPLUGIN_H
#define SOFAORCOMMONPLUGIN_H

#include <sofa/helper/system/config.h>

#define SOFAORCOMMONPLUGIN_MAJOR_VERSION \
  $ { SOFAORCOMMONPLUGIN_MAJOR_VERSION }
#define SOFAORCOMMONPLUGIN_MINOR_VERSION \
  $ { SOFAORCOMMONPLUGIN_MINOR_VERSION }
#ifdef SOFA_BUILD_SOFAORCOMMONPLUGIN
#define SOFA_TARGET SofaORCommonPlugin
#define SOFA_SOFAORCOMMONPLUGIN_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#define SOFA_SOFAORCOMMONPLUGIN_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif

#endif  // SOFA_BUILD_SOFAORCOMMONPLUGIN
